name: Check Typos

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  typos:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install typos CLI
        run: |
          mkdir -p $HOME/.local/bin
          curl -LsSf https://github.com/crate-ci/typos/releases/download/v1.30.0/typos-v1.30.0-x86_64-unknown-linux-musl.tar.gz | tar xzf - -C $HOME/.local/bin
          chmod +x $HOME/.local/bin/typos
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Fix typos
        id: fix-typos
        run: |
          typos --write-changes
          if [ -n "$(git status --porcelain)" ]; then
            echo "changes_made=true" >> $GITHUB_OUTPUT
          else
            echo "changes_made=false" >> $GITHUB_OUTPUT
          fi

      - name: Create PR
        if: steps.fix-typos.outputs.changes_made == 'true'
        uses: peter-evans/create-pull-request@v5
        with:
          commit-message: 'fix: correct typos in codebase'
          title: 'Fix: Typo Corrections'
          body: |
            ## 📝 Automated Typo Fixes
            This PR contains automated fixes for typos found in the codebase.
          branch: fix-typos
          delete-branch: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
