name: Check Typos

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  typos:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Check Typos
        uses: crate-ci/typos@v1.16.23
        id: typos
        with:
          write_changes: true

      - name: Create PR
        if: steps.typos.outcome == 'failure'
        uses: peter-evans/create-pull-request@v5
        with:
          commit-message: 'fix: correct typos in codebase'
          title: 'Fix: Typo Corrections'
          body: |
            ## 📝 Automated Typo Fixes
            This PR contains automated fixes for typos found in the codebase.
          branch: fix-typos
          delete-branch: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
